gammaray: add elfutils to DEPENDS
all of a sudden, the recipe broke, leaving only this sort of a message:

```
ld: error: .../recipe-sysroot-native/usr/lib/libdw.so: incompatible target
3rdparty/backward-cpp/backward.hpp:...: error: undefined reference to 'dw...'
(repeated for a shitton of other symbols)
```